In [57]:
import pandas as pd

In [58]:
df = pd.read_csv(r'C:\Users\HP\Desktop\Pandas\data\survey_results_public.csv', low_memory=False, index_col='ResponseId')
schema_df = pd.read_csv(r'C:\Users\HP\Desktop\Pandas\data\survey_results_schema.csv', index_col="qname")

In [59]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [60]:
df.shape

(49191, 171)

In [61]:
df.info(verbose= True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 1 to 49191
Data columns (total 171 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    MainBranch                                49191 non-null  str
 1    Age                                       49191 non-null  str
 2    EdLevel                                   48149 non-null  str
 3    Employment                                48339 non-null  str
 4    EmploymentAddl                            44875 non-null  str
 5    WorkExp                                   42893 non-null  float64
 6    LearnCodeChoose                           46858 non-null  str
 7    LearnCode                                 33556 non-null  str
 8    LearnCodeAI                               45201 non-null  str
 9    AILearnHow                                28257 non-null  str
 10   YearsCode                                 43042 non-null  float64
 11   DevType                                   43680 non-null  str
 12   OrgSize                                   34178 non-null  str
 13   ICorPM                                    33243 non-null  str
 14   RemoteWork                                33780 non-null  str
 15   PurchaseInfluence                         37437 non-null  str
 16   TechEndorseIntro                          37556 non-null  str
 17   TechEndorse_1                             35975 non-null  float64
 18   TechEndorse_2                             35975 non-null  float64
 19   TechEndorse_3                             35975 non-null  float64
 20   TechEndorse_4                             35975 non-null  float64
 21   TechEndorse_5                             35975 non-null  float64
 22   TechEndorse_6                             35975 non-null  float64
 23   TechEndorse_7                             35975 non-null  float64
 24   TechEndorse_8                             35975 non-null  float64
 25   TechEndorse_9                             35975 non-null  float64
 26   TechEndorse_13                            35975 non-null  float64
 27   TechEndorse_13_TEXT                       2009 non-null   str
 28   TechOppose_1                              34259 non-null  float64
 29   TechOppose_2                              34259 non-null  float64
 30   TechOppose_3                              34259 non-null  float64
 31   TechOppose_5                              34259 non-null  float64
 32   TechOppose_7                              34259 non-null  float64
 33   TechOppose_9                              34259 non-null  float64
 34   TechOppose_11                             34259 non-null  float64
 35   TechOppose_13                             34259 non-null  float64
 36   TechOppose_16                             34259 non-null  float64
 37   TechOppose_15                             34259 non-null  float64
 38   TechOppose_15_TEXT                        1647 non-null   str
 39   Industry                                  33642 non-null  str
 40   JobSatPoints_1                            24943 non-null  float64
 41   JobSatPoints_2                            24943 non-null  float64
 42   JobSatPoints_3                            24943 non-null  float64
 43   JobSatPoints_4                            24943 non-null  float64
 44   JobSatPoints_5                            24943 non-null  float64
 45   JobSatPoints_6                            24943 non-null  float64
 46   JobSatPoints_7                            24943 non-null  float64
 47   JobSatPoints_8                            24943 non-null  float64
 48   JobSatPoints_9                            24943 non-null  float64
 49   JobSatPoints_10                           24943 non-null  float64
 50   JobSatPoints_11                           24943 non-null  float64
 51   JobSatPoints_13                           24943 non-null  float64
 52   JobSatPoints_14                           24943 non-null  float64
 53   JobSatPoints_15                           24943 non-null  float64
 54   JobSatPoints_16                           24943 non-null  float64
 55   JobSatPoints_15_TEXT                      664 non-null    str
 56   AIThreat                                  36078 non-null  str
 57   NewRole                                   35527 non-null  str
 58   ToolCountWork                             27611 non-null  float64
 59   ToolCountPersonal                         25582 non-null  float64
 60   Country                                   35437 non-null  str
 61   Currency                                  35437 non-null  str
 62   CompTotal                                 24866 non-null  float64
 63   LanguageChoice                            32214 non-null  str
 64   LanguageHaveWorkedWith                    31671 non-null  str
 65   LanguageWantToWorkWith                    27079 non-null  str
 66   LanguageAdmired                           23470 non-null  str
 67   LanguagesHaveEntry                        3982 non-null   str
 68   LanguagesWantEntry                        3150 non-null   str
 69   DatabaseChoice                            31688 non-null  str
 70   DatabaseHaveWorkedWith                    25550 non-null  str
 71   DatabaseWantToWorkWith                    19733 non-null  str
 72   DatabaseAdmired                           17295 non-null  str
 73   DatabaseHaveEntry                         2150 non-null   str
 74   DatabaseWantEntry                         1533 non-null   str
 75   PlatformChoice                            31262 non-null  str
 76   PlatformHaveWorkedWith                    24258 non-null  str
 77   PlatformWantToWorkWith                    19415 non-null  str
 78   PlatformAdmired                           17822 non-null  str
 79   PlatformHaveEntry                         3957 non-null   str
 80   PlatformWantEntry                         3100 non-null   str
 81   WebframeChoice                            31193 non-null  str
 82   WebframeHaveWorkedWith                    22992 non-null  str
 83   WebframeWantToWorkWith                    17639 non-null  str
 84   WebframeAdmired                           15709 non-null  str
 85   WebframeHaveEntry                         3294 non-null   str
 86   WebframeWantEntry                         2630 non-null   str
 87   DevEnvsChoice                             31079 non-null  str
 88   DevEnvsHaveWorkedWith                     26019 non-null  str
 89   DevEnvsWantToWorkWith                     20614 non-null  str
 90   DevEnvsAdmired                            19492 non-null  str
 91   DevEnvHaveEntry                           2762 non-null   str
 92   DevEnvWantEntry                           2112 non-null   str
 93   SOTagsHaveWorkedWith                      17922 non-null  str
 94   SOTagsWantToWorkWith                      13587 non-null  str
 95   SOTagsAdmired                             12240 non-null  str
 96   SOTagsHaveEntry                           458 non-null    str
 97   SOTagsWant Entry                          430 non-null    str
 98   OpSysPersonal use                         31417 non-null  str
 99   OpSysProfessional use                     28883 non-null  str
 100  OfficeStackAsyncHaveWorkedWith            29858 non-null  str
 101  OfficeStackAsyncWantToWorkWith            23206 non-null  str
 102  OfficeStackAsyncAdmired                   22208 non-null  str
 103  OfficeStackHaveEntry                      2589 non-null   str
 104  OfficeStackWantEntry                      1617 non-null   str
 105  CommPlatformHaveWorkedWith                30065 non-null  str
 106  CommPlatformWantToWorkWith                23351 non-null  str
 107  CommPlatformAdmired                       22877 non-null  str
 108  CommPlatformHaveEntr                      1476 non-null   str
 109  CommPlatformWantEntr                      1184 non-null   str
 110  AIModelsChoice                            30239 non-null  str
 111  AIModelsHaveWorkedWith                    16281 non-null  str
 112  AIModelsWantToWorkWith                    11845 non-null  str
 113  AIModelsAdmired                           11284 non-null  str
 114  AIModelsHaveEntry                         776 non-null    str
 115  AIModelsWantEntry                         475 non-null    str
 116  SOAccount                                 32797 non-null  str
 117  SOVisitFreq                               32710 non-null  str
 118  SODuration                                32627 non-null  str
 119  SOPartFreq                                32228 non-null  str
 120  SO_Dev_Content                            22836 non-null  str
 121  SO_Actions_1                              26260 non-null  float64
 122  SO_Actions_16                             24340 non-null  float64
 123  SO_Actions_3                              26260 non-null  float64
 124  SO_Actions_4                              26260 non-null  float64
 125  SO_Actions_5                              26260 non-null  float64
 126  SO_Actions_6                              26260 non-null  float64
 127  SO_Actions_9                              26260 non-null  float64
 128  SO_Actions_7                              26260 non-null  float64
 129  SO_Actions_10                             26260 non-null  float64
 130  SO_Actions_15                             26260 non-null  float64
 131  SO_Actions_15_TEXT                        823 non-null    str
 132  SOComm                                    31706 non-null  str
 133  SOFriction                                30787 non-null  str
 134  AISelect                                  33720 non-null  str
 135  AISent                                    33467 non-null  str
 136  AIAcc                                     33297 non-null  str
 137  AIComplex                                 33283 non-null  str
 138  AIToolCurrently partially AI              21028 non-null  str
 139  AIToolDon't plan to use AI for this task  25381 non-null  str
 140  AIToolPlan to partially use AI            22556 non-null  str
 141  AIToolPlan to mostly use AI               12818 non-null  str
 142  AIToolCurrently mostly AI                 11225 non-null  str
 143  AIFrustration                             31522 non-null  str
 144  AIExplain                                 26586 non-null  str
 145  AIAgents                                  31919 non-null  str
 146  AIAgentChange                             31678 non-null  str
 147  AIAgent_Uses                              12320 non-null  str
 148  AgentUsesGeneral                          5805 non-null   str
 149  AIAgentImpactSomewhat agree               10146 non-null  str
 150  AIAgentImpactNeutral                      9675 non-null   str
 151  AIAgentImpactSomewhat disagree            5791 non-null   str
 152  AIAgentImpactStrongly agree               6687 non-null   str
 153  AIAgentImpactStrongly disagree            3779 non-null   str
 154  AIAgentChallengesNeutral                  21295 non-null  str
 155  AIAgentChallengesSomewhat disagree        12125 non-null  str
 156  AIAgentChallengesStrongly agree           23108 non-null  str
 157  AIAgentChallengesSomewhat agree           21947 non-null  str
 158  AIAgentChallengesStrongly disagree        9314 non-null   str
 159  AIAgentKnowledge                          3401 non-null   str
 160  AIAgentKnowWrite                          766 non-null    str
 161  AIAgentOrchestration                      3760 non-null   str
 162  AIAgentOrchWrite                          478 non-null    str
 163  AIAgentObserveSecure                      2692 non-null   str
 164  AIAgentObsWrite                           264 non-null    str
 165  AIAgentExternal                           8332 non-null   str
 166  AIAgentExtWrite                           859 non-null    str
 167  AIHuman                                   29194 non-null  str
 168  AIOpen                                    22540 non-null  str
 169  ConvertedCompYearly                       23947 non-null  float64
 170  JobSat                                    26670 non-null  float64
dtypes: float64(52), str(119)
memory usage: 64.2 MB

In [62]:
pd.set_option('display.max_columns' , None)
pd.set_option('display.max_rows' , 170)

In [63]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [64]:
df.shape

(49191, 171)

In [65]:
pd.set_option('display.max_columns', None)

In [66]:
print(list(df.columns))

['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow', 'YearsCode', 'DevType', 'OrgSize', 'ICorPM', 'RemoteWork', 'PurchaseInfluence', 'TechEndorseIntro', 'TechEndorse_1', 'TechEndorse_2', 'TechEndorse_3', 'TechEndorse_4', 'TechEndorse_5', 'TechEndorse_6', 'TechEndorse_7', 'TechEndorse_8', 'TechEndorse_9', 'TechEndorse_13', 'TechEndorse_13_TEXT', 'TechOppose_1', 'TechOppose_2', 'TechOppose_3', 'TechOppose_5', 'TechOppose_7', 'TechOppose_9', 'TechOppose_11', 'TechOppose_13', 'TechOppose_16', 'TechOppose_15', 'TechOppose_15_TEXT', 'Industry', 'JobSatPoints_1', 'JobSatPoints_2', 'JobSatPoints_3', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'JobSatPoints_13', 'JobSatPoints_14', 'JobSatPoints_15', 'JobSatPoints_16', 'JobSatPoints_15_TEXT', 'AIThreat', 'NewRole', 'ToolCountWork', 'ToolCountPersonal', 'Country', 'Currency', 'CompTotal', 'LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry', 'DatabaseChoice', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired', 'DatabaseHaveEntry', 'DatabaseWantEntry', 'PlatformChoice', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired', 'PlatformHaveEntry', 'PlatformWantEntry', 'WebframeChoice', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired', 'WebframeHaveEntry', 'WebframeWantEntry', 'DevEnvsChoice', 'DevEnvsHaveWorkedWith', 'DevEnvsWantToWorkWith', 'DevEnvsAdmired', 'DevEnvHaveEntry', 'DevEnvWantEntry', 'SOTagsHaveWorkedWith', 'SOTagsWantToWorkWith', 'SOTagsAdmired', 'SOTagsHaveEntry', 'SOTagsWant Entry', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackAsyncAdmired', 'OfficeStackHaveEntry', 'OfficeStackWantEntry', 'CommPlatformHaveWorkedWith', 'CommPlatformWantToWorkWith', 'CommPlatformAdmired', 'CommPlatformHaveEntr', 'CommPlatformWantEntr', 'AIModelsChoice', 'AIModelsHaveWorkedWith', 'AIModelsWantToWorkWith', 'AIModelsAdmired', 'AIModelsHaveEntry', 'AIModelsWantEntry', 'SOAccount', 'SOVisitFreq', 'SODuration', 'SOPartFreq', 'SO_Dev_Content', 'SO_Actions_1', 'SO_Actions_16', 'SO_Actions_3', 'SO_Actions_4', 'SO_Actions_5', 'SO_Actions_6', 'SO_Actions_9', 'SO_Actions_7', 'SO_Actions_10', 'SO_Actions_15', 'SO_Actions_15_TEXT', 'SOComm', 'SOFriction', 'AISelect', 'AISent', 'AIAcc', 'AIComplex', 'AIToolCurrently partially AI', "AIToolDon't plan to use AI for this task", 'AIToolPlan to partially use AI', 'AIToolPlan to mostly use AI', 'AIToolCurrently mostly AI', 'AIFrustration', 'AIExplain', 'AIAgents', 'AIAgentChange', 'AIAgent_Uses', 'AgentUsesGeneral', 'AIAgentImpactSomewhat agree', 'AIAgentImpactNeutral', 'AIAgentImpactSomewhat disagree', 'AIAgentImpactStrongly agree', 'AIAgentImpactStrongly disagree', 'AIAgentChallengesNeutral', 'AIAgentChallengesSomewhat disagree', 'AIAgentChallengesStrongly agree', 'AIAgentChallengesSomewhat agree', 'AIAgentChallengesStrongly disagree', 'AIAgentKnowledge', 'AIAgentKnowWrite', 'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure', 'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman', 'AIOpen', 'ConvertedCompYearly', 'JobSat']

In [67]:
df['Employment'].value_counts()

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

In [68]:
df.loc[0:2, 'Employment':'LearnCode']

,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode
ResponseId,,,,,
1,Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...
2,Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...

In [69]:
schema_df.loc['LearnCodeChoose', 'question']

'Did you begin learning to code or learn a new coding skill/programming language in the last year?'

In [70]:
# schema_df.sort_index(ascending=False)
schema_df.sort_index(inplace=True)

In [71]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [72]:
high_sal = (df['ConvertedCompYearly'] > 70000)

In [73]:
# df.loc[high_sal, ['Country', 'LanguageAdmired', 'ConvertedCompYearly']]
# countries = ['United States of America', 'India', 'Canada', 'United Kingdom']

In [74]:
# df.loc[filt, 'Country']

In [75]:
# filt = pd.DataFrame(filt)

In [76]:
# df['Country'].value_counts()

In [77]:
# filt = df[df['Country'].isin(countries)]

In [78]:
# filt['Country'].value_counts()

In [79]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
# df['LanguageAdmired']

In [80]:
filt

ResponseId
1        False
2        False
3        False
4        False
5         True
         ...
49187    False
49188    False
49189    False
49190    False
49191    False
Name: LanguageHaveWorkedWith, Length: 49191, dtype: bool

In [81]:
df.rename(columns={'ConvertedCompYearly' : 'SalaryUSD'})

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [82]:
df['ConvertedCompYearly']

ResponseId
1         61256.0
2        104413.0
3         53061.0
4         36197.0
5         60000.0
           ...
49187         NaN
49188         NaN
49189         NaN
49190         NaN
49191         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [83]:
df['Employment'].map({'Yes':True, 'No':False})

ResponseId
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
        ...
49187    NaN
49188    NaN
49189    NaN
49190    NaN
49191    NaN
Name: Employment, Length: 49191, dtype: object

In [84]:
df.isnull()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,True,False,False,True,True,True,True,False,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False,False,True,True,False,True,True,True,True,False,False,True,True,True,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,False,True,True,True,False,True,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,True,False,True,True,True,True,True,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,True,True,True,True,True,False,True,True,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,True,True,True,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,True,True,True,True,True,True,True,False,True,False,True,False,False
5,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49188,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
49190,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49191,False,False,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [85]:
df.isnull().sum()

MainBranch                 0
Age                        0
EdLevel                 1042
Employment               852
EmploymentAddl          4316
                       ...
AIAgentExtWrite        48332
AIHuman                19997
AIOpen                 26651
ConvertedCompYearly    25244
JobSat                 22521
Length: 171, dtype: int64

In [86]:
df.isnull().sum().sum()

np.int64(4437549)

## Filling Null Values

In [87]:
df2 = df.fillna(value = 0)

In [88]:
df2

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,0,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,0,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,0,0,Yes,Cloud Firestore;PostgreSQL,0,0,0,0,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,0,0,0,0,No,0,0,0,0,0,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,0,0,0,0,0,0,0,0,0,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,0,0,"Stack Overflow;Reddit;GitHub (public projects,...",0,0,0,0,Yes,openAI GPT (chatbot models);openAI Image gener...,0,0,0,0,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,0,1.0,0.0,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,0,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,0,0,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,0,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,0,0,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,0,0,0,0,Vertex AI,0,0,0,ChatGPT,0,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,0,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,0,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,0,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,0,0,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,0,0,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,0,0,Yes,Spring Boot,Spring Boot,Spring Boot,0,0,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,0,0,0,0,0,0,0,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,0,0,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,0,0,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),0,0,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,0.0,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,0,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,0,0,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,0,0,0,0,0,0,0,It takes significant time and effort to learn ...,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,0,0,0,0,0,0,0,0,0,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",0,0,0,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,0,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,0,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,0,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,0,0,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,0,0,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,0,0,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,0,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,0,0,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,0,0,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,0,0,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,0,0,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,0,0,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,0.0,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,0,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,0,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,0,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,0,0,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,0,I am concerned about the accuracy of the infor...,0,Redis,0,0,0,0,0,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,0,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,0,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,0,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,0,No,I have neither consider or transitioned into a...,0.0,0.0,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,0,0,No,0,0,0,0,0,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,0,0,Yes,Spring Boot,Spring Boot,Spring Boot,0,0,No,0,0,0,0,0,Amazon Bedrock,0,0,0,0,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,0,0,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,0,0,No,0,0,0,0,0,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,0.0,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,0,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,0,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,0,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,0,0,It takes significant time and effort to learn ...,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,0,0,0,0,0,0,0,ChatGPT;Claude Code,0,When I don’t trust AI’s answers;When I want to...,0,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",0,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,0,0,0,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,0,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,0,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,0,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,0,0,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,0,0,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,0,0,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,0,0,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,0,0,Large Language Model;Google Gemini,Large Language Model,Large Language Model,0,0,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,0,0,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,0,0,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),0,0,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,0.0,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,0,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,0,0,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",0,0,0,0,0,0,0,Integrating AI agents with my existing tools a...,0,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,0,0,0,0,0,0,0,0,0,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,0,0.0,0,0,0,0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,0,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,0,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,0,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,0,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,0,0,0,0,0,0,AI agents have increased my productivity.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0

df2.isnull().sum().sum()

In [89]:
df3 = df.fillna(value = 5)

In [90]:
df3

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,5,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,5,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,5,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,5,5,Yes,Cloud Firestore;PostgreSQL,5,5,5,5,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,5,5,5,5,No,5,5,5,5,5,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,5,5,5,5,5,5,5,5,5,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,5,5,"Stack Overflow;Reddit;GitHub (public projects,...",5,5,5,5,Yes,openAI GPT (chatbot models);openAI Image gener...,5,5,5,5,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,5,1.0,5.0,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,5,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,5,5,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,5,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,5,5,5,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,5,5,5,5,Vertex AI,5,5,5,ChatGPT,5,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,5,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,5,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,5,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,5,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,5,5,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,5,5,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,5,5,Yes,Spring Boot,Spring Boot,Spring Boot,5,5,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,5,5,5,5,5,5,5,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,5,5,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,5,5,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),5,5,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,5.0,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,5,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,5,5,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,5,5,5,5,5,5,5,It takes significant time and effort to learn ...,5,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,5,5,5,5,5,5,5,5,5,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",5,5,5,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,5,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,5,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,5,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,5,5,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,5,5,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,5,5,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,5,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,5,5,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,5,5,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,5,5,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,5,5,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,5,5,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,5.0,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,5,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,5,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,5,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,5,5,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,5,I am concerned about the accuracy of the infor...,5,Redis,5,5,5,5,5,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,5,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,5,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,5,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,5,No,I have neither consider or transitioned into a...,5.0,5.0,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,5,5,No,5,5,5,5,5,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,5,5,Yes,Spring Boot,Spring Boot,Spring Boot,5,5,No,5,5,5,5,5,Amazon Bedrock,5,5,5,5,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,5,5,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,5,5,No,5,5,5,5,5,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,5.0,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,5,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,5,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,5,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,5,5,It takes significant time and effort to learn ...,5,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,5,5,5,5,5,5,5,ChatGPT;Claude Code,5,When I don’t trust AI’s answers;When I want to...,5,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",5,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,5,5,5,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,5,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,5,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,5,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,5,5,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,5,5,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,5,5,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,5,5,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,5,5,Large Language Model;Google Gemini,Large Language Model,Large Language Model,5,5,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,5,5,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,5,5,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),5,5,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,5.0,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,5,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,5,5,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",5,5,5,5,5,5,5,Integrating AI agents with my existing tools a...,5,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,5,5,5,5,5,5,5,5,5,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,5,5.0,5,5,5,5,5.0,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5.0,5.0,5,5,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",5,5.0,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5.0,5.0,5,5,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,5,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,5,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,5,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,5,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,5,5,5,5,5,5,AI agents have increased my productivity.,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",5,5.0,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5.0,5.0,5,5,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5.0,5.0

## Filling Null Values with previous values

In [91]:
df4 = df.ffill()

In [92]:
df4.isnull().sum().sum()

np.int64(3363)

## Filling Null values with next valid values

In [93]:
df5 = df.bfill()

In [94]:
df5.isnull().sum().sum()

np.int64(3023)