In [2]:
person = {
    "first" : "Haseeb",
    "last" : "Tariq",
    "email" : "haseebtariq@gmail.com"
}

In [3]:
people = {
    "first" : ["Haseeb"],
    "last" : ["Tariq"],
    "email" : ["haseebtariq@gmail.com"]
}

In [4]:
people = {
    "first" : ["Haseeb", "Ali", "Sharjeel"],
    "last" : ["Tariq", "Ahmad", "Ikhlaq"],
    "email" : ["haseebtariq@gmail.com", "aliahmad@gmail.com", "sharjeelikhlaq@gmail.com"]
}

In [5]:
people["email"]

['haseebtariq@gmail.com', 'aliahmad@gmail.com', 'sharjeelikhlaq@gmail.com']

In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.DataFrame(people)

In [8]:
df

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
1       Ali   Ahmad        aliahmad@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [9]:
df.email

0       haseebtariq@gmail.com
1          aliahmad@gmail.com
2    sharjeelikhlaq@gmail.com
Name: email, dtype: str

In [10]:
df[['last', 'email']]

     last                     email
0   Tariq     haseebtariq@gmail.com
1   Ahmad        aliahmad@gmail.com
2  Ikhlaq  sharjeelikhlaq@gmail.com

In [11]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [12]:
df.iloc[[0, 1], 2]

0    haseebtariq@gmail.com
1       aliahmad@gmail.com
Name: email, dtype: str

In [13]:
df.loc[0]

first                   Haseeb
last                     Tariq
email    haseebtariq@gmail.com
Name: 0, dtype: str

In [14]:
# df.loc[[0,1], ['email', 'last']]

In [15]:
df['email']

0       haseebtariq@gmail.com
1          aliahmad@gmail.com
2    sharjeelikhlaq@gmail.com
Name: email, dtype: str

In [16]:
# df.set_index('email', inplace=True)

In [17]:
df

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
1       Ali   Ahmad        aliahmad@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [18]:
# df.index

In [19]:
# df.loc['haseebtariq@gmail.com', 'last']

In [20]:
df.iloc[0]

first                   Haseeb
last                     Tariq
email    haseebtariq@gmail.com
Name: 0, dtype: str

In [21]:
df

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
1       Ali   Ahmad        aliahmad@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [22]:
# df.reset_index(inplace=True)

In [23]:
# filt = (df['last'] == 'Ikhlaq') & (df['first'] == 'Haseeb')
filt = (df['last'] == 'Ikhlaq') | (df['first'] == 'Haseeb')

In [24]:
df[filt]

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [25]:
df.loc[~filt, 'email']

1    aliahmad@gmail.com
Name: email, dtype: str

In [26]:
df.columns = ['first_name', 'last_name', 'email']
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [27]:
df.columns = [x.upper() for x in df.columns]

In [28]:
df.columns

Index(['FIRST_NAME', 'LAST_NAME', 'EMAIL'], dtype='str')

In [29]:
df

  FIRST_NAME LAST_NAME                     EMAIL
0     Haseeb     Tariq     haseebtariq@gmail.com
1        Ali     Ahmad        aliahmad@gmail.com
2   Sharjeel    Ikhlaq  sharjeelikhlaq@gmail.com

In [30]:
df.columns = [x.lower() for x in df.columns]

In [31]:
df

  first_name last_name                     email
0     Haseeb     Tariq     haseebtariq@gmail.com
1        Ali     Ahmad        aliahmad@gmail.com
2   Sharjeel    Ikhlaq  sharjeelikhlaq@gmail.com

In [32]:
df.rename(columns={'first_name' : 'first', 'last_name' : 'last'}, inplace=True)

In [33]:
df

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
1       Ali   Ahmad        aliahmad@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [34]:
df.loc[1] = ['Zeeshan', 'Jamal', 'zeeshan@gmail.com']

In [35]:
df

      first    last                     email
0    Haseeb   Tariq     haseebtariq@gmail.com
1   Zeeshan   Jamal         zeeshan@gmail.com
2  Sharjeel  Ikhlaq  sharjeelikhlaq@gmail.com

In [67]:
df.loc[2, ['last', 'email']] = ['Hussain', 'Sharjeel@gmail.com']

In [68]:
df

      first     last                  email
0    Haseeb    Tariq  haseebtariq@gmail.com
1   Zeeshan    Jamal      zeeshan@gmail.com
2  Sharjeel  Hussain     Sharjeel@gmail.com

In [69]:
df.loc[2, 'last'] = 'Sheikh'
df

      first    last                  email
0    Haseeb   Tariq  haseebtariq@gmail.com
1   Zeeshan   Jamal      zeeshan@gmail.com
2  Sharjeel  Sheikh     Sharjeel@gmail.com

In [70]:
df.at[2, 'last'] = 'Sheikh'
df

      first    last                  email
0    Haseeb   Tariq  haseebtariq@gmail.com
1   Zeeshan   Jamal      zeeshan@gmail.com
2  Sharjeel  Sheikh     Sharjeel@gmail.com

In [71]:
filt = (df['email'] == 'sharjeel@gmail.com')
df[filt]['last']

Series([], Name: last, dtype: str)

In [72]:
filt = (df['email'] == 'sharjeel@gmail.com')
df.loc[filt, 'last'] = 'Ikhklaq'

In [73]:
df

      first    last                  email
0    Haseeb   Tariq  haseebtariq@gmail.com
1   Zeeshan   Jamal      zeeshan@gmail.com
2  Sharjeel  Sheikh     Sharjeel@gmail.com

In [75]:
df['email'] = df['email'].str.lower()

In [76]:
df

      first    last                  email
0    Haseeb   Tariq  haseebtariq@gmail.com
1   Zeeshan   Jamal      zeeshan@gmail.com
2  Sharjeel  Sheikh     sharjeel@gmail.com

In [78]:
df['email'].apply(len)

0    21
1    17
2    18
Name: email, dtype: int64

In [79]:
def update_email(email):
    return email.upper()

In [80]:
df['email'].apply(update_email)

0    HASEEBTARIQ@GMAIL.COM
1        ZEESHAN@GMAIL.COM
2       SHARJEEL@GMAIL.COM
Name: email, dtype: str

In [81]:
df['email'] = df['email'].apply(update_email)

In [82]:
df

      first    last                  email
0    Haseeb   Tariq  HASEEBTARIQ@GMAIL.COM
1   Zeeshan   Jamal      ZEESHAN@GMAIL.COM
2  Sharjeel  Sheikh     SHARJEEL@GMAIL.COM

In [84]:
df['email'] = df['email'].apply(lambda x: x.lower())

In [85]:
df

      first    last                  email
0    Haseeb   Tariq  haseebtariq@gmail.com
1   Zeeshan   Jamal      zeeshan@gmail.com
2  Sharjeel  Sheikh     sharjeel@gmail.com

In [87]:
df['email'].apply(len)

0    21
1    17
2    18
Name: email, dtype: int64

In [90]:
df.apply(len, axis='rows')

first    3
last     3
email    3
dtype: int64

In [91]:
len(df['email'])

3

In [92]:
df.apply(pd.Series.min)

first                   Haseeb
last                     Jamal
email    haseebtariq@gmail.com
dtype: str

In [94]:
df.apply(lambda x: x.min())

first                   Haseeb
last                     Jamal
email    haseebtariq@gmail.com
dtype: str

In [96]:
df.map(len)

   first  last  email
0      6     5     21
1      7     5     17
2      8     6     18

In [100]:
df.map(str.lower)

      first    last                  email
0    haseeb   tariq  haseebtariq@gmail.com
1   zeeshan   jamal      zeeshan@gmail.com
2  sharjeel  sheikh     sharjeel@gmail.com

In [102]:
df['first'].map({'Haseeb' : 'Muneeb', 'Zeeshan' : 'Arham', 'Sharjeel' : 'Sultan'})

0    Muneeb
1     Arham
2    Sultan
Name: first, dtype: str

In [104]:
df['first'] = df['first'].replace({'Haseeb' : 'Muneeb', 'Zeeshan' : 'Arham', 'Sharjeel' : 'Sultan'})

In [106]:
df

    first    last                  email
0  Muneeb   Tariq  haseebtariq@gmail.com
1   Arham   Jamal      zeeshan@gmail.com
2  Sultan  Sheikh     sharjeel@gmail.com

In [109]:
df['first']+ '' + df['last']

0     MuneebTariq
1      ArhamJamal
2    SultanSheikh
dtype: str

In [112]:
df['full_name'] = df['first']+ ' ' + df['last']

In [113]:
df

    first    last                  email      full_name
0  Muneeb   Tariq  haseebtariq@gmail.com   Muneeb Tariq
1   Arham   Jamal      zeeshan@gmail.com    Arham Jamal
2  Sultan  Sheikh     sharjeel@gmail.com  Sultan Sheikh

In [117]:
df.drop(columns=['first', 'last'], inplace=True)

In [118]:
df

                   email      full_name
0  haseebtariq@gmail.com   Muneeb Tariq
1      zeeshan@gmail.com    Arham Jamal
2     sharjeel@gmail.com  Sultan Sheikh

In [120]:
df['full_name'].str.split(' ', expand=True)

        0       1
0  Muneeb   Tariq
1   Arham   Jamal
2  Sultan  Sheikh

In [122]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)

In [123]:
df

                   email      full_name   first    last
0  haseebtariq@gmail.com   Muneeb Tariq  Muneeb   Tariq
1      zeeshan@gmail.com    Arham Jamal   Arham   Jamal
2     sharjeel@gmail.com  Sultan Sheikh  Sultan  Sheikh